### PR TITLE
fix: ZomeManifest and AppRoleDnaManifest types, remove Location type

### LINKED ISSUE #377: ZomeManifest definition is broken
It doesn't match the Rust definition in Holochain 0.6 which makes calls to updateCoordinators fail because of failed request deserialization.
Please fix.

JS type: https://github.com/holochain/holochain-client-js/blob/3b087397b8eefdbd9b1348b8d318b4547cc948ae/src/api/admin/types.ts#L774

### PR DESCRIPTION
**Pull request by matthme**
### Summary
Fixes #377 

### TODO:
- [ ] CHANGELOG mentions all code changes.
- [ ] docs have been updated (`npm run build:docs`)

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed type definitions for AppRoleDnaManifest and ZomeManifest to properly represent manifest structure.

* **Documentation**
  * Updated API documentation to reflect changes in manifest type signatures and removed deprecated type definitions.

### CODE REVIEW

File: src/api/admin/types.ts [hunk 1]
```diff
@@ -424,10 +401,11 @@ export type DnaVersionFlexible =
  * @public
  */
 export type AppRoleDnaManifest = {
-  clone_limit?: number;
```
Comment (matthme) [inline src/api/admin/types.ts:427]: This just got moved below to use the same ordering as the type in the holochain repo.

File: src/api/admin/types.ts [hunk 2]
```diff
@@ -383,29 +383,6 @@ export interface CellProvisioning {
   deferred?: boolean;
 }
 
-/**
- * @public
- */
-export type Location =
```
Comment (matthme) [inline src/api/admin/types.ts:389]: Not in use anymore.

**Review by ThetaSinner — APPROVED** [review]

**Review by jost-s — APPROVED** [review]
LGTM

File: docs/client.approlednamanifest.md [hunk 3]
```diff
@@ -9,10 +9,11 @@
 
 ```typescript
 export type AppRoleDnaManifest = {
-    clone_limit?: number;
+    path?: string;
     modifiers?: Partial<DnaModifiers>;
-    version?: DnaVersionFlexible;
-} & Location;
+    installed_hash?: DnaHash;
+    clone_limit?: number;
```
Comment (mattyg) [inline docs/client.approlednamanifest.md:15]:
```suggestion
    clone_limit: number;
```

I think the default of 0 only applies when loading the manifest via serde.

Comment (matthme) [reply docs/client.approlednamanifest.md:15]: Are you sure about this? Doesn't it do that as part of the Deserialize trait?

Comment (matthme) [reply docs/client.approlednamanifest.md:15]: If the default wouldn't work then [this test](https://github.com/holochain/holochain-client-js/blob/3b087397b8eefdbd9b1348b8d318b4547cc948ae/test/e2e/index.ts#L529-L532) which doesn't specify `clone_limit` should fail with a deserialisation error.

File: src/api/admin/types.ts [hunk 4]
```diff
@@ -424,10 +401,11 @@ export type DnaVersionFlexible =
...
  */
 export type AppRoleDnaManifest = {
-  clone_limit?: number;
+  path?: string;
   modifiers?: Partial<DnaModifiers>;
-  version?: DnaVersionFlexible;
-} & Location;
+  installed_hash?: DnaHash;
+  clone_limit?: number;
+};
```
[the remark this answers is not in the document]
Comment (matthme) [reply src/api/admin/types.ts:408]: The AppRoleDnaManifest implements the serde Serialize and Deserialize traits which take care of filling up the default.
