### PR TITLE
Test/assert is direct

### LINKED ISSUE #407: Add assertion for transport properties
There is a test to dump network stats, but it doesn't assert all fields of the types in the result. `is_direct` of the connection stats must be asserted in particular, to prevent regressions.

**Tasks:**
- Add assertion `is_direct in connection_stats` or `connection_stats.is_direct === false` (must not be `!connection_stats.is_direct` to prevent `undefined` comparison)
- Check that all other properties of the types are asserted too

### PR DESCRIPTION
**Pull request by mattyg**
### Summary
Resolves #407 

### TODO:
- [x] CHANGELOG mentions all code changes.
- [ ] docs have been updated (`npm run build:docs`)

## Release Notes

* **Bug Fixes**
  * Corrected return type handling for network statistics API to properly reflect response structure.

* **New Features**
  * Added `decodeHashFromBase64` utility function for decoding base64-encoded identifiers to byte arrays.

* **Tests**
  * Migrated test framework to vitest for improved performance and maintainability.
  * Enhanced network statistics validation with comprehensive batch testing scenarios.

### CODE REVIEW

File: test/e2e/index.ts [hunk 1]
```diff
@@ -1391,24 +1393,46 @@ test(
 
 test(
   "can dump network stats",
-  withConductor(ADMIN_PORT, async (t) => {
-    const { admin, client } = await installAppAndDna(ADMIN_PORT);
+  withConductorBatch([ADMIN_PORT, ADMIN_PORT+1], async (t) => {
```
Comment (jost-s) [inline test/e2e/index.ts]:
```suggestion
  withConductorBatch([ADMIN_PORT, ADMIN_PORT + 1], async (t) => {
```

**Review by jost-s — DISMISSED** [review]
sweet as!

**Review by veeso — DISMISSED** [review]

File: test/e2e/index.ts (hunk 1 above)
Comment (mattyg) [reply test/e2e/index.ts]: fixed

**Review by jost-s — DISMISSED** [review]

**Comment by mattyg** [comment]
I will rebase this after #410 is merged, as the tests are still timing out the github runner.

**Review by veeso — DISMISSED** [review]

**Review by ThetaSinner — DISMISSED** [review]

**Review by jost-s — APPROVED** [review]
